server:
  port: 9090

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luizfelipew/delivery-configs
