server:
  port: 9092


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_app?autoReconnect=true&useSSL=false
    username: springuser_app
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    tomcat:
      max-active: 1


  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
      database-platform: org.hibernate.dialect.MySQLDialect
      show-sql: true
      hibernate:
        ddl-auto: none
